### ISSUE TITLE
Small error in documentation 

### ISSUE THREAD

**Issue by reconlap** [druu/ci-presenter#7]
You load your presenter with that object

$this->load->library('presenter');
$data['presenter'] = $this->presenter->create('example', $objs);

should it not read 

$this->data['presenter'] = $this->presenter->create('example', $objs);

**Comment by druu** [comment]
$this->data['presenter']   would be okay if we were using Jamie Rumbelow's Base Controller with View-Autoloading.

Since my examples are built on a clean CI-Setup $data['presenter'] is fine b/c we're passing the $data array to the view.
Additionally the rest of the Controller isn't shown, so we're assuming a basic Controller extending CI_Controller, with no additional properties.
